-- Shift V1 cloud-sync schema
-- Run this in a dedicated Shift Supabase project.

create table if not exists public.shift_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state_json jsonb not null default '{"threads":[],"activeId":null}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.shift_state enable row level security;

create policy "Users can read their own Shift state"
on public.shift_state for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert their own Shift state"
on public.shift_state for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own Shift state"
on public.shift_state for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own Shift state"
on public.shift_state for delete
to authenticated
using ((select auth.uid()) = user_id);

-- Optional public, source-backed guidance catalog. Keep personal user data out of this table.
create table if not exists public.guidance_items (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  category text not null,
  title text not null,
  summary text not null,
  source_url text,
  source_name text,
  source_checked_at timestamptz,
  jurisdiction text,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.guidance_items enable row level security;

create policy "Published guidance is publicly readable"
on public.guidance_items for select
to anon, authenticated
using (is_published = true);
